### ISSUE TITLE
Command does not work 

### ISSUE THREAD

**Issue by Calvinoux** [Rachnus/SuperHero-Mod-CSGO#1]
Hello it look amazing, great work, thank you ! 
but i have a issue, when i type any command it say in console Unknown command, 
Plugins are running, it is loaded and checked sm plugins list
in chat it show : 

 [SuperHero] LVL: 0/10 XP: (0/100)
 [SuperHero] LVL: 0/10 XP: (0/100)

All files is well uploaded

Running on sourcemod lastest stable build (6025)

**Comment by jimppan** [comment]
Which commands? If you're trying to type !heroes or !showmenu when you're level 0 or do not have any heroes to choose, you cannot use that command

EDIT: Nvm im blind, you said any command. Hmm, I will try reinstall the plugin on my server with the release build and see what happends. I compiled this plugin on latest dev build btw

EDIT2: I forgot to include the main translation file... its added now though (addons/sourcemod/translations/superheromod.phrases.txt)

**Comment by Calvinoux** [comment]
Working, thank you!
