### ISSUE TITLE
Morpheus hero animation bug

### ISSUE THREAD

**Issue by Calvinoux** [Rachnus/SuperHero-Mod-CSGO#2]
Hello, 

Morpheus hero seem to be buggy, i try to explain:
 the bullet's impact and sound for dual MP5 (Morpheus) isn't work properly ( its like you shoot 1 bullet at a time and slowly) but in reality you shoot too fast then u can't not see the impact and sound, i think it is a csgo issue? is it possible to fix it? would be great.. :S

**Comment by jimppan** [comment]
I could just make the mp7 have normal fire rate and just double the damage instead, add me on steam if u want btw http://steamcommunity.com/profiles/76561198020758610/

**Comment by Calvinoux** [comment]
It is a bit different, if damage x2, the hero will be too strong i think, since you need only 1 bullet instead of 2 + without the delay that the second bullet need to touch the player (also the accurate is more efficient if u shoot 1 bullet instead of 2) 

by this way, it like  swap a secondary hero to a "must have" and i think its better to have diversity and not to see everyone with MP7 :D 

Isn't it possible to reduce a bit the firerate, so the engine can work properly?
I guess the actual firerate is +100% (x2) 

maybe reduce it to +50% or 40% ?
